export { default as albumRoutes } from "./album.routes.js";
export { default as artistRoutes } from "./artist.routes.js";
export { default as authRoutes } from "./auth.routes.js";
export { default as playlistRoutes } from "./playlist.routes.js";
export { default as proxyRoutes } from "./proxy.routes.js";
export { default as songRoutes } from "./song.routes.js";
export { default as userRoutes } from "./user.routes.js";
export { default as searchRoutes } from "./search.routes.js";
export { default as reportRoutes } from "./report.routes.js";
