name: Build and deploy Node.js app to Azure Web App - cosc-3380

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install server dependencies for build
        run: |
          cd server
          npm install

      - name: Install client dependencies
        run: |
          cd client
          npm install --legacy-peer-deps

      - name: Build server and client
        run: npm run build

      - name: Install production dependencies in dist
        run: |
          cd server/dist
          npm install 

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cosc-3380"
          slot-name: "Production"
          package: server/dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_48CEDE4FE3CF4F1F91BAFF928283B051 }}
