name: Build and deploy Node.js app to Azure Web App - cosc-3380

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      # Build frontend
      - name: Install and build frontend
        run: |
          cd client
          npm install --legacy-peer-deps
          npm run build
          cd ..

      # Build backend
      - name: Install and build backend
        run: |
          cd server
          npm install
          npm run build
          cd ..

      # Create deployment package
      - name: Create deployment package
        run: |
          mkdir -p deployment

          # Copy React build to public/ folder (NOT dist/)
          cp -r client/dist/* deployment/public/

          # Copy server.cjs from server build output
          cp server/dist/server.cjs deployment/

          # Copy package.json from server (NOT package-lock.json)
          cp server/package.json deployment/

          # Install production dependencies to create node_modules
          cd deployment
          npm install
          cd ..

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cosc-3380"
          slot-name: "Production"
          package: deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_48CEDE4FE3CF4F1F91BAFF928283B051 }}
